# Rozhranie
rtp_ui_cam_distance=Vzdialenosť kamery:
rtp_ui_cam_up=Výška kamery:
rtp_ui_cam_right=Horizontálny posun:
rtp_ui_cam_fov=Zorné pole (FOV):
rtp_ui_zoom_fov=Miera priblíženia pri mierení:
rtp_ui_aiming_btn=Tlačidlo namierenia:
rtp_ui_sens_mult=Citlivosť kamery:
rtp_ui_hide_crosshair=Skryť zameriavač bez mierenia
rtp_ui_trace_crosshair=Dynamický 3D zameriavač
rtp_ui_toggle_aim=Mierenie na kliknutie (Toggle)
rtp_ui_smart_scope=Inteligentné mierenie (vypnuté u sniperov)
rtp_ui_invert_y=Prevrátiť os Y
rtp_ui_classic_mode=Klasický pohyb (fixný ku kamere)
rtp_ui_reset_btn=Obnoviť predvolené
rtp_ui_enable_btn=Zapnúť pohľad tretej osoby
rtp_ui_disable_btn=Vypnúť pohľad tretej osoby

# Nápovedy
rtp_tip_cam_distance=Zaisťuje kontrolu nad tým, ako ďaleko za chrbtom postavy sa nachádza kamera.
rtp_tip_cam_up=Nastavuje, či bude pohľad umiestnený vyššie, alebo nižšie voči ramenám tvojho hráča.
rtp_tip_cam_right=Presúva zorný bod vľavo alebo vpravo od stredovej osi tvojej hernej postavy.
rtp_tip_cam_fov=Upravuje šírku zorného uhla na obrazovke v momente hrania za tretiu osobu.
rtp_tip_zoom_fov=Ovplyvňuje silu zväčšenia pohľadu vo chvíli, kedy namieriš svojou zbraňou.
rtp_tip_aiming_btn=Priradenie špecifickej klávesy na klávesnici alebo tlačidla myši určeného na mierene strieľanie.
rtp_tip_sens_mult=Násobiteľ rýchlosti kamery (1 = predvolené, < 1 pomalšie, > 1 rýchlejšie).
rtp_tip_hide_crosshair=Odoberie známy krížik v strede hernej obrazovky pre realistickejší zážitok, pokiaľ nestrieľaš.
rtp_tip_trace_crosshair=Kalkuluje prekážky a posúva nitkový kríž priamo na miesto dopadu projektilu pomocou 3D lúča.
rtp_tip_toggle_aim=Ak nechceš neustále držať gombík myši pri zamierení, takto ho aktivuješ len obyčajným klikom.
rtp_tip_smart_scope=Automaticky prispôsobí kameru a hodí ťa do první osoby počas pohľadu do optiky odstreľovačky.
rtp_tip_invert_y=Kompletne otáča zvislý smer kamery - ťah myšou hore pozerá dole (podobné leteckým hrám).
rtp_tip_classic_mode=Udržuje telo tvojej hernej postavy permanentne nasmerované rovnakým smerom ako mieri tvoja obrazovka.
