# Rozhraní
rtp_ui_cam_distance=Vzdálenost kamery:
rtp_ui_cam_up=Výška kamery:
rtp_ui_crouch_drop=Snížení kamery při přikrčení:
rtp_ui_cam_right=Horizontální posun:
rtp_ui_cam_fov=Zorné pole (FOV):
rtp_ui_zoom_fov=Míra přiblížení při míření:
rtp_ui_aiming_btn=Tlačítko míření:
rtp_ui_sens_mult=Citlivost kamery:
rtp_ui_hide_crosshair=Skrýt zaměřovač bez míření
rtp_ui_trace_crosshair=Dynamický 3D zaměřovač
rtp_ui_crosshair_size=Velikost zaměřovače:
rtp_ui_crosshair_color=Barva zaměřovače:
rtp_ui_toggle_aim=Míření na kliknutí (Toggle)
rtp_ui_smart_scope=Chytré míření (vypnuto u sniperů)
rtp_ui_smart_scope_threshold=Prahová hodnota FOV pro Smart Scope:
rtp_ui_invert_y=Převrátit osu Y
rtp_ui_classic_mode=Klasický pohyb (fixní ke kameře)
rtp_ui_reset_btn=Obnovit výchozí
rtp_ui_enable_btn=Zapnout pohled třetí osoby
rtp_ui_disable_btn=Vypnout pohled třetí osoby

# Nápovědy
rtp_tip_cam_distance=Určuje, jak daleko se má kamera nacházet za zády tvé postavy.
rtp_tip_cam_up=Nastavuje, jak vysoko nad ramenem postavy bude pohled kamery umístěn.
rtp_tip_crouch_drop=O kolik se kamera sníží při přikrčení hráče. (0 = bez snížení)
rtp_tip_cam_right=Zajišťuje možnost posunutí kamery doleva nebo doprava oproti středu zad.
rtp_tip_cam_fov=Mění základní úhel zorného pole hráče při hraní ve třetí osobě.
rtp_tip_zoom_fov=Zvyšuje intenzitu přiblížení zbraně, jakmile stiskneš klávesu přesného míření.
rtp_tip_aiming_btn=Tlačítko na tvé klávesnici nebo myši využívané pro režim míření.
rtp_tip_sens_mult=Násobitel rychlosti kamery (1 = výchozí, < 1 pomalejší, > 1 rychlejší).
rtp_tip_hide_crosshair=Zcela odstraní výchozí zaměřovací kříž, pokud pouze utíkáš a nemíříš.
rtp_tip_trace_crosshair=Vykreslí přesný bod dopadu kulky promítnutý reálně v 3D světě hry.
rtp_tip_crosshair_size=Upravuje velikost (délku) vlastního dynamického zaměřovače.
rtp_tip_crosshair_color=Upravuje barvu a neprůhlednost vlastního dynamického zaměřovače.
rtp_tip_toggle_aim=Díky zapnutí stačí stisknout tlačítko pouze jednou pro míření, aniž bys ho držel.
rtp_tip_smart_scope=Při podívání se do hledí odstřelovací pušky tě tvůrce vrhne zpět do vlastních očí (1st person).
rtp_tip_smart_scope_threshold=Nastavuje prahovou hodnotu FOV, pod kterou se Smart Scope automaticky přepne do pohledu první osoby.
rtp_tip_invert_y=Obrátí směr pohledu nahoru a dolů tak, jak to preferují tvůrci leteckých simulátorů.
rtp_tip_classic_mode=Zamkne pohyb hráče takovým způsobem, že tělo se vždy točí tam, kam se díváš.
