# Kasutajaliides
rtp_ui_cam_distance=Kaamera kaugus:
rtp_ui_cam_up=Kaamera kõrgus:
rtp_ui_crouch_drop=Kaamera langus kükitamisel:
rtp_ui_cam_right=Horisontaalne nihe:
rtp_ui_cam_fov=Vaateväli (FOV):
rtp_ui_zoom_fov=Suumi tugevus sihtimisel:
rtp_ui_aiming_btn=Sihtimise nupp:
rtp_ui_sens_mult=Kaamera tundlikkus:
rtp_ui_hide_crosshair=Peida sihik, kui ei sihitata
rtp_ui_trace_crosshair=Dünaamiline 3D sihik
rtp_ui_crosshair_size=Sihiku suurus:
rtp_ui_crosshair_color=Sihiku värv:
rtp_ui_toggle_aim=Klõpsa sihtimiseks (Lülita)
rtp_ui_smart_scope=Nutikas sihtimine (snaipritel keelatud)
rtp_ui_smart_scope_threshold=Smart Scope FOV lävi:
rtp_ui_invert_y=Pööra Y-telg ümber
rtp_ui_classic_mode=Klassikaline liikumine (lukustatud kaamerale)
rtp_ui_reset_btn=Algseaded
rtp_ui_enable_btn=Luba kolmas isik
rtp_ui_disable_btn=Keela kolmas isik

# Vihjed
rtp_tip_cam_distance=Määrab, kui kaugel mängija selja tagant kaamera asub.
rtp_tip_cam_up=Reguleerib kaamera kõrgust tegelaskuju õlgade suhtes.
rtp_tip_crouch_drop=Kui palju kaamera langeb, kui mängija kükitab. (0 = ei lange)
rtp_tip_cam_right=Võimaldab kaamerat nihutada tegelaskujust vasakule või paremale.
rtp_tip_cam_fov=Määrab teie üldise vaatevälja laiuse kolmandas isikus.
rtp_tip_zoom_fov=Määrab, kui tugevasti suumitakse sisse, kui sihtimisnuppu all hoiate.
rtp_tip_aiming_btn=Valib hiire- või klaviatuurinupu, mis aktiveerib täpse sihtimise.
rtp_tip_sens_mult=Kaamera kiiruse kordaja (1 = vaikimisi, < 1 aeglasem, > 1 kiirem).
rtp_tip_hide_crosshair=Eemaldab ekraanilt tavalise ristikuho, kui relva ei hoita palges.
rtp_tip_trace_crosshair=Joonistab täpse 3D-punkti, mis näitab kuuli tegelikku tabamiskohta ruumis.
rtp_tip_crosshair_size=Kohandab kohandatud dünaamilise sihiku suurust (pikkust).
rtp_tip_crosshair_color=Kohandab kohandatud dünaamilise sihiku värvi ja läbipaistvust.
rtp_tip_toggle_aim=Võimaldab sihtimise sisse ja välja lülitada ühe klõpsuga, ilma nuppu all hoidmata.
rtp_tip_smart_scope=Lülitub automaatselt esimese isiku vaatesse, kui vaatate läbi snaiperpüssi optika.
rtp_tip_smart_scope_threshold=Määrab FOV läve, millest allpool lülitub Smart Scope automaatselt esimese isiku vaatesse.
rtp_tip_invert_y=Pöörab vertikaalse kaamera juhtimise pea peale (nagulennusimulaatorites).
rtp_tip_classic_mode=Sunnib tegelaskuju keha pöörama alati selles suunas, kuhu kaamera vaatab.
