# ממשק משתמש
rtp_ui_cam_distance=מרחק מצלמה:
rtp_ui_cam_up=גובה מצלמה:
rtp_ui_crouch_drop=ירידת מצלמה בכריעה:
rtp_ui_cam_right=היסט אופקי:
rtp_ui_cam_fov=שדה ראייה (FOV):
rtp_ui_zoom_fov=עוצמת תקריב (זום):
rtp_ui_aiming_btn=לחצן כיוון נשק:
rtp_ui_sens_mult=רגישות מצלמה:
rtp_ui_hide_crosshair=הסתר כוונת ללא נשק במצב כיוון
rtp_ui_trace_crosshair=כוונת תלת-ממדית דינאמית
rtp_ui_crosshair_size=גודל כוונת:
rtp_ui_crosshair_color=צבע כוונת:
rtp_ui_toggle_aim=לחיצה אחת לכיוון נשק (טוגל)
rtp_ui_smart_scope=כוונת חכמה (מבוטלת ברובי צלפים)
rtp_ui_smart_scope_threshold=סף FOV עבור Smart Scope:
rtp_ui_invert_y=הפוך את ציר ה-Y
rtp_ui_classic_mode=תנועה קלאסית (נעולה למצלמה)
rtp_ui_reset_btn=איפוס הגדרות
rtp_ui_enable_btn=הפעל גוף שלישי
rtp_ui_disable_btn=השבת גוף שלישי

# טיפים
rtp_tip_cam_distance=שולט במרחק המצלמה מגבו של השחקן שלך.
rtp_tip_cam_up=קובע האם המצלמה תמוקם גבוה מעל הכתף או באותו הגובה.
rtp_tip_crouch_drop=כמה המצלמה יורדת כשהשחקן כורע. (0 = ללא ירידה)
rtp_tip_cam_right=מזיז את המצלמה שמאלה או ימינה ממרכז גופו של השחקן.
rtp_tip_cam_fov=מגדיר עד כמה רחב יהיה שדה הראייה הכולל במבט גוף שלישי.
rtp_tip_zoom_fov=קובע את עוצמת תקריב המצלמה כשאתה לוחץ על כפתור הכיוון המדויק.
rtp_tip_aiming_btn=הכפתור בעכבר או במקלדת שישמש לכניסה למצב כיוון מדויק.
rtp_tip_sens_mult=מכפיל מהירות מצלמה (1 = ברירת מחדל, < 1 לאט יותר, > 1 מהר יותר).
rtp_tip_hide_crosshair=מעלים את צלב הכוונת הסטנדרטי כאשר אינך פועל במצב של כיוון צלפים או קליעה.
rtp_tip_trace_crosshair=משרטט נקודת פגיעה מציאותית המחשבת מכשולים ומראה היכן באמת יפגע הקליע בתוך המפה.
rtp_tip_crosshair_size=מכוונן את הגודל (האורך) של הכוונת הדינמית המותאמת אישית.
rtp_tip_crosshair_color=מכוונן את הצבע והאטימות של הכוונת הדינמית המותאמת אישית.
rtp_tip_toggle_aim=משנה את ההתנהגות כך שלחיצה אחת תשאיר אותך במצב כיוון במקום הצורך להחזיק את הכפתור.
rtp_tip_smart_scope=מחזיר אוטומטית לגוף ראשון כשמעלים כוונת טלסקופית, בכדי למנוע הסתרה של המטרה על ידי גופך.
rtp_tip_smart_scope_threshold=מגדיר את סף ה-FOV שמתחתיו ה-Smart Scope עובר אוטומטית למבט גוף ראשון.
rtp_tip_invert_y=הופך את השליטה האנכית של המצלמה כלפי מטה כשהעכבר זז למעלה, בדומה לסימולטור טיסה.
rtp_tip_classic_mode=מאלץ את המודל לראות ולא כיוון רק לכיוון אליו מופנית המצלמה.
