# Елементи на интерфейса
rtp_ui_cam_distance=Разстояние на камерата:
rtp_ui_cam_up=Височина на камерата:
rtp_ui_cam_right=Хоризонтално изместване:
rtp_ui_cam_fov=Зрително поле (FOV):
rtp_ui_zoom_fov=Увеличение при прицелване:
rtp_ui_aiming_btn=Бутон за прицелване:
rtp_ui_sens_mult=Чувствителност на камерата:
rtp_ui_hide_crosshair=Скриване на мерника (без прицелване)
rtp_ui_trace_crosshair=Динамичен 3D мерник
rtp_ui_crosshair_size=Размер на мерника:
rtp_ui_crosshair_color=Цвят на мерника:
rtp_ui_toggle_aim=Прицелване с клик (Toggle)
rtp_ui_smart_scope=Умен мерник (изкл. снайпери)
rtp_ui_smart_scope_threshold=Праг на FOV за Smart Scope:
rtp_ui_invert_y=Обърната Y-Ос
rtp_ui_classic_mode=Класическо движение (свързано с камерата)
rtp_ui_reset_btn=Възстановяване по подразбиране
rtp_ui_enable_btn=Включи трето лице
rtp_ui_disable_btn=Изключи трето лице

# Подсказки
rtp_tip_cam_distance=Контролира колко далеч зад гърба на героя се намира камерата.
rtp_tip_cam_up=Регулира височината на камерата спрямо раменете на героя.
rtp_tip_cam_right=Измества погледа на камерата наляво или надясно от центъра.
rtp_tip_cam_fov=Задава общата ширина на вашето зрителното поле.
rtp_tip_zoom_fov=Определя колко се приближава екрана, когато държите бутона за прицелване.
rtp_tip_aiming_btn=Изберете кой клавиш или бутон на мишката да служи за прецизно прицелване.
rtp_tip_sens_mult=Множител на скоростта на камерата (1 = по подразбиране, < 1 по-бавно, > 1 по-бързо).
rtp_tip_hide_crosshair=Скрива стандартния мерник от екрана, освен ако не активирате точно прицелване.
rtp_tip_trace_crosshair=Показва реален маркер, сочещ точно къде ще попадне куршумът в 3D пространството.
rtp_tip_crosshair_size=Променя размера (дължината) на персонализирания динамичен мерник.
rtp_tip_crosshair_color=Променя цвета и прозрачността на персонализирания динамичен мерник.
rtp_tip_toggle_aim=Позволява влизане в режим на прицелване с едно кликване, без да задържате бутона.
rtp_tip_smart_scope=Играта автоматично превключва в първо лице, когато гледате през далекоглед на снайпер.
rtp_tip_smart_scope_threshold=Задава прага на FOV, под който Smart Scope автоматично превключва към първо лице.
rtp_tip_invert_y=Обръща вертикалното управление за любителите на летателни симулатори наопаки.
rtp_tip_classic_mode=Принуждава модела на героя постоянно да се върти по посока на погледа на камерата.
