# Sąsaja
rtp_ui_cam_distance=Kameros atstumas:
rtp_ui_cam_up=Kameros aukštis:
rtp_ui_crouch_drop=Kameros nusileidimas atsitūpus:
rtp_ui_cam_right=Horizontalus nuokrypis:
rtp_ui_cam_fov=Matymo laukas (FOV):
rtp_ui_zoom_fov=Priartinimo stiprumas:
rtp_ui_aiming_btn=Taikymosi mygtukas:
rtp_ui_sens_mult=Kameros jautrumas:
rtp_ui_hide_crosshair=Slėpti taikiklį nesitaikant
rtp_ui_trace_crosshair=Dinaminis 3D taikiklis
rtp_ui_crosshair_size=Taikiklio dydis:
rtp_ui_crosshair_color=Taikiklio spalva:
rtp_ui_toggle_aim=Taikymasis vienu paspaudimu
rtp_ui_smart_scope=Išmanus taikiklis (išjungta snaiperiams)
rtp_ui_invert_y=Ciklo Y ašies apvertimas
rtp_ui_classic_mode=Klasikinis judėjimas (pririšta prie kameros)
rtp_ui_reset_btn=Grąžinti numatytuosius parametrus
rtp_ui_enable_btn=Įjungti trečio asmens vaizdą
rtp_ui_disable_btn=Išjungti trečio asmens vaizdą
rtp_ui_aim_rot_speed=Sukimosi greitis nusitaikius:
rtp_ui_transition_speed=Kameros perėjimo greitis
rtp_ui_block_attack2=Blokuoti ginklo alternatyvią ugnį taikantis

# Patarimai
rtp_tip_cam_distance=Nustato, kaip toli už veikėjo nugaros atsiduria kamera.
rtp_tip_cam_up=Reguliuoja kameros padėtį aukščiau arba žemiau žaidėjo pečių.
rtp_tip_crouch_drop=Kiek kamera nusileidžia, kai žaidėjas atsitūpia. (0 = nenusileidžia)
rtp_tip_cam_right=Nustato, ar kamera bus pasislinkus į kairę, ar į dešinę veikėjo pusę.
rtp_tip_cam_fov=Suteikia galimybę keisti bendro matymo lauko plotį trečio asmens rėžime.
rtp_tip_zoom_fov=Kontroliuoja vaizdo priartinimo lygį, kai laikote nuspaudę taikymosi mygtuką.
rtp_tip_aiming_btn=Paskiria pelės arba klaviatūros mygtuką, kurį paspaudus įjungiamas tikslus ginklo taikiklis.
rtp_tip_sens_mult=Kameros greičio daugiklis (1 = numatytasis, < 1 lėčiau, > 1 greičiau).
rtp_tip_hide_crosshair=Paslepia standartinį taikiklio kryželį ekrano centre, kai ginklas nėra nukreiptas.
rtp_tip_trace_crosshair=Rodomas specialus žymiklis, atspindintis tikslią kulkos smūgio vietą atsižvelgiant į fizikines kliūtis 3D erdvėje.
rtp_tip_crosshair_size=Koreguoja pritaikyto dinaminio taikiklio dydį (ilgį).
rtp_tip_crosshair_color=Koreguoja pritaikyto dinaminio taikiklio spalvą ir nepermatomumą.
rtp_tip_toggle_aim=Taikymosi būsena užrakinama vieną kartą spustelėjus mygtuką – nereikia jo nuolat laikyti nuspausto.
rtp_tip_smart_scope=Automatiškai grąžina į pirmo asmens vaizdą naudojant snaiperio optiką, kad veikėjo kūnas neužstotų taikinio.
rtp_tip_invert_y=Apverčia vertikalų kameros judėjimą lėktuvų simuliatoriaus stiliumi.
rtp_tip_classic_mode=Taiso veikėjo modelio orientaciją taip, kad jis visuomet žiūrėtų tik ten, kur atsukta kamera.
rtp_tip_aim_rot_speed=Veikėjo sukimosi sklandumas nusitaikant.
rtp_tip_transition_speed=Kinematografinio kameros skrydžio greitis. Nustatykite 0, norėdami momentinio perjungimo.
rtp_tip_block_attack2=Neleidžia šaudyti ginklo antrine ataka taikantis iš trečiojo asmens. Išjunkite tai, jei taikymasis sugadina pritaikytas ginklų bazes, pvz., ARC9.
