# Arayüz
rtp_ui_cam_distance=Kamera Mesafesi:
rtp_ui_cam_up=Kamera Yüksekliği:
rtp_ui_crouch_drop=Eğilme Kamera Düşüşü:
rtp_ui_cam_right=Yatay Kamera Kaydırma:
rtp_ui_cam_fov=Görüş Alanı (FOV):
rtp_ui_zoom_fov=Nişan Yakınlaştırma Miktarı:
rtp_ui_aiming_btn=Nişan Alma Tuşu:
rtp_ui_sens_mult=Kamera Hassasiyeti:
rtp_ui_hide_crosshair=Gez/Göz Gezdirmiyorsan Nişangahı Gizle
rtp_ui_trace_crosshair=Dinamik 3D Vuruş Nişangahı
rtp_ui_crosshair_size=Nişangah Boyutu:
rtp_ui_crosshair_color=Nişangah Rengi:
rtp_ui_toggle_aim=Tıkla Nişan Al (Aç-Kapa)
rtp_ui_smart_scope=Akıllı Dürbün (Keskin Nişancılar İçin İptal)
rtp_ui_invert_y=Y-Ekseni Ters Çevir
rtp_ui_classic_mode=Klasik Hareket (Kameraya kitli)
rtp_ui_reset_btn=Ayarları Sıfırla
rtp_ui_enable_btn=Üçüncü Şahsı Aç
rtp_ui_disable_btn=Üçüncü Şahsı Kapat

# İpuçları
rtp_tip_cam_distance=Kameranın karakterin arkasında ne kadar uzakta duracağını belirler.
rtp_tip_cam_up=Kameranın yüksekliğini, oyuncunun omuz hizasına veya tepesine göre ayarlar.
rtp_tip_crouch_drop=Oyuncu eğilirken kameranın ne kadar aşağı ineceği. (0 = düşüş yok)
rtp_tip_cam_right=Kamerayı karakterin sağına veya soluna kaydırarak konumlandırır.
rtp_tip_cam_fov=Üçüncü şahıs (Third Person) modundaki geniş görüş açısını düzenler.
rtp_tip_zoom_fov=Nişan alma tuşuna basıldığında ekranın ne kadar yakınlaşacağını seçer.
rtp_tip_aiming_btn=Silahla yakından nişan almak için farenin veya klavyenin hangi tuşunu kullanacağını ayarlar.
rtp_tip_sens_mult=Kamera hızı çarpanı (1 = varsayılan, < 1 daha yavaş, > 1 daha hızlı).
rtp_tip_hide_crosshair=Silah aktif bir şekilde ateş etmek için kaldırılmamışsa ekrandaki nişangah işaretini saklar.
rtp_tip_trace_crosshair=Merminin fiziksel olarak tam nereye çarpacağını gösteren daha gerçekçi bir nişangah çizer.
rtp_tip_crosshair_size=Özel dinamik nişangahın boyutunu (uzunluğunu) ayarlar.
rtp_tip_crosshair_color=Özel dinamik nişangahın rengini ve saydamlığını ayarlar.
rtp_tip_toggle_aim=Nişan almak için tuşa basılı tutmak yerine, sadece bir kez tıklayarak nişan alma moduna girmeyi ve çıkmayı sağlar.
rtp_tip_smart_scope=Uzun menzilli silah dürbünlerini açtığınızda görüşün modelle kapanmaması için kamerayı anında birinci şahıs (First Person) moduna çeker.
rtp_tip_invert_y=Uçak simülasyonu seven oyuncular için dikey kamera hareketinin yönünü tersine çevirir.
rtp_tip_classic_mode=Karakterin vücudunun kameranın baktığı yöne doğru zorla dönmesini sağlayan orijinal mekaniği açar.
