# Brugergrænseflade
rtp_ui_cam_distance=Kamera Afstand:
rtp_ui_cam_up=Kamera Højde:
rtp_ui_crouch_drop=Kamerasænkning i hug:
rtp_ui_cam_right=Horisontal Forskydning:
rtp_ui_cam_fov=Synsfelt (FOV):
rtp_ui_zoom_fov=Zoommængde ved sigte:
rtp_ui_aiming_btn=Sigtetast:
rtp_ui_sens_mult=Kamerafølsomhed:
rtp_ui_hide_crosshair=Skjul sigtekorn uden aktivt sigte
rtp_ui_trace_crosshair=Dynamisk 3D-sigtekorn (Kuglebane)
rtp_ui_crosshair_size=Sigtekornets størrelse:
rtp_ui_crosshair_color=Sigtekornets farve:
rtp_ui_toggle_aim=Skift sigte ved klik (Toggle)
rtp_ui_smart_scope=Smart Sigte (deaktiveret ved snigskytte)
rtp_ui_invert_y=Omvendt Y-Akse
rtp_ui_classic_mode=Klassisk bevægelse (Låst til kameraet)
rtp_ui_reset_btn=Nulstil
rtp_ui_enable_btn=Slå Tredjeperson Til
rtp_ui_disable_btn=Slå Tredjeperson Fra

# Værktøjstip
rtp_tip_cam_distance=Styrer, hvor langt væk fra din karakters ryg kameraet er placeret.
rtp_tip_cam_up=Justerer højden for kameraet i forhold til din spillers skuldre.
rtp_tip_crouch_drop=Hvor meget kameraet sænkes, når spilleren sidder på hug. (0 = ingen sænkning)
rtp_tip_cam_right=Betyder, hvor meget kameraet skal forskydes mod venstre eller højre for spilleren.
rtp_tip_cam_fov=Indstiller den grundlæggende bredde af dit samlede synsfelt i tředjeperson formen.
rtp_tip_zoom_fov=Styrer styrken af indzoomningen, når knappen for detaljeret sigte holdes nede.
rtp_tip_aiming_btn=Vælger den mus- eller tastaturknap, som aktiverer sigtetilstanden.
rtp_tip_sens_mult=Kamerahastighedsmultiplikator (1 = standard, < 1 langsommere, > 1 hurtigere).
rtp_tip_hide_crosshair=Fjerner sigtekornet fra centrum af skærmen, når dit våben er i hvileposition.
rtp_tip_trace_crosshair=Tegner et super-nøjagtigt kryds, som tager højde for 3D objekter under beskydningen.
rtp_tip_crosshair_size=Justerer størrelsen (længden) af det brugerdefinerede dynamiske sigtekorn.
rtp_tip_crosshair_color=Justerer farven og gennemsigtigheden af det brugerdefinerede dynamiske sigtekorn.
rtp_tip_toggle_aim=Klik én gang for at sigte vedvarende fremfor at holde knappen trykket ind konstant.
rtp_tip_smart_scope=Skifter nemt tilbage til førsteperson, når der kigges igennem snigskytterifler, for friere udsyn.
rtp_tip_invert_y=Vender funktionerne for den vertikale musebevægelse om som forventet i flysimulatorer.
rtp_tip_classic_mode=Konfigurerer spillermodelens krop til kun at kune pege i samme retning som spillerens synspunkt.
