# Felület
rtp_ui_cam_distance=Kamera távolsága:
rtp_ui_cam_up=Kamera magassága:
rtp_ui_crouch_drop=Kamera süllyedése guggoláskor:
rtp_ui_cam_right=Vízszintes eltolás:
rtp_ui_cam_fov=Látószög (FOV):
rtp_ui_zoom_fov=Célzáskori nagyítás:
rtp_ui_aiming_btn=Célzó gomb:
rtp_ui_sens_mult=Kamera érzékenysége:
rtp_ui_hide_crosshair=Célkereszt elrejtése célzás nélkül
rtp_ui_trace_crosshair=Dinamikus 3D célkereszt
rtp_ui_crosshair_size=Célkereszt mérete:
rtp_ui_crosshair_color=Célkereszt színe:
rtp_ui_toggle_aim=Célzás kattintással (Toggle)
rtp_ui_smart_scope=Okos célzás (kikapcsolás mesterlövésznél)
rtp_ui_invert_y=Y tengely megfordítása
rtp_ui_classic_mode=Klasszikus mozgás (kamerához rögzítve)
rtp_ui_reset_btn=Alapértelmezések
rtp_ui_enable_btn=Külső nézet bekapcsolása
rtp_ui_disable_btn=Külső nézet kikapcsolása

# Tippek
rtp_tip_cam_distance=Szabályozza, hogy a kamera mennyire legyen távol a karaktered hátától.
rtp_tip_cam_up=Beállítja a kamera magasságát a játékos vállához viszonyítva.
rtp_tip_crouch_drop=Mennyivel süllyedjen a kamera, amikor a játékos guggol. (0 = nincs süllyedés)
rtp_tip_cam_right=Balra vagy jobbra tolja el a kamerát a karakter középvonalától.
rtp_tip_cam_fov=Megadja a teljes látószög (FOV) szélességét külső nézetben.
rtp_tip_zoom_fov=Meghatározza a képernyő nagyításának mértékét a célzó gomb nyomva tartásakor.
rtp_tip_aiming_btn=Kiválasztja az egér vagy a billentyűzet gombját a precíziós célzáshoz.
rtp_tip_sens_mult=Kamera sebességszorzó (1 = alapértelmezett, < 1 lassabb, > 1 gyorsabb).
rtp_tip_hide_crosshair=Eltávolítja az alapértelmezett célkeresztet a képernyőről, amikor a fegyvered nyugalmi állapotban van.
rtp_tip_trace_crosshair=Egy valós idejű célkeresztet rajzol ki, amely megmutatja a golyó becsapódásának tényleges helyét a 3D térben.
rtp_tip_crosshair_size=Beállítja az egyéni dinamikus célkereszt méretét (hosszát).
rtp_tip_crosshair_color=Beállítja az egyéni dinamikus célkereszt színét és átlátszatlanságát.
rtp_tip_toggle_aim=A gomb nyomva tartása helyett egy kattintással kapcsolhatod be és ki a célzást.
rtp_tip_smart_scope=Mesterlövész puskák távcsövén keresztül nézve automatikusan visszavált a belső nézetre a pontosabb lövés érdekében.
rtp_tip_invert_y=Megfordítja a kamera függőleges mozgását a repülőszimulátorokhoz hasonlóan.
rtp_tip_classic_mode=A karaktered teste mindig abba az irányba fog fordulni és nézni, amerre a kamera mutat.
