# Interfejs
rtp_ui_cam_distance=Dystans kamery:
rtp_ui_cam_up=Wysokość kamery:
rtp_ui_crouch_drop=Obniżenie kamery podczas kucania:
rtp_ui_cam_right=Przesunięcie w poziomie:
rtp_ui_cam_fov=Kąt widzenia (FOV):
rtp_ui_zoom_fov=Przybliżenie celowania:
rtp_ui_aiming_btn=Przycisk celowania:
rtp_ui_sens_mult=Czułość kamery:
rtp_ui_hide_crosshair=Ukryj celownik bez celowania
rtp_ui_trace_crosshair=Dynamiczny celownik 3D
rtp_ui_crosshair_size=Rozmiar celownika:
rtp_ui_crosshair_color=Kolor celownika:
rtp_ui_toggle_aim=Celowanie na kliknięcie (Toggle)
rtp_ui_smart_scope=Inteligentny celownik (wył. w snajperkach)
rtp_ui_invert_y=Odwróć oś Y
rtp_ui_classic_mode=Klasyczny ruch (przypięty do kamery)
rtp_ui_reset_btn=Zresetuj ustawienia
rtp_ui_enable_btn=Włącz widok TPP
rtp_ui_disable_btn=Wyłącz widok TPP
rtp_ui_aim_rot_speed=Prędkość obrotu podczas celowania:
rtp_ui_transition_speed=Prędkość przejścia kamery

# Podpowiedzi
rtp_tip_cam_distance=Kontroluje, jak daleko z tyłu postaci znajduje się kamera.
rtp_tip_cam_up=Określa, na jakiej wysokości względem ramienia gracza znajduje się punkt widzenia.
rtp_tip_crouch_drop=O ile kamera obniża się, gdy gracz kuca. (0 = brak obniżenia)
rtp_tip_cam_right=Pozwala przesunąć kamerę bardziej w lewą lub prawą stronę postaci.
rtp_tip_cam_fov=Ustala ogólną szerokość widzenia w trybie trzecioosobowym.
rtp_tip_zoom_fov=Decyduje, jak mocno obraz zostanie zbliżony podczas ręcznego celowania z broni.
rtp_tip_aiming_btn=Wybiera klawisz lub przycisk myszy odpowiedzialny za precyzyjne celowanie.
rtp_tip_sens_mult=Mnożnik prędkości kamery (1 = domyślnie, < 1 wolniej, > 1 szybciej).
rtp_tip_hide_crosshair=Dezaktywuje standardowy krzyżyk na środku ekranu, gdy nie mierzysz z broni.
rtp_tip_trace_crosshair=Rysuje realistyczny wskaźnik trafienia kuli w świecie trójwymiarowym, ignorując sam środek ekranu.
rtp_tip_crosshair_size=Dostosowuje rozmiar (długość) niestandardowego celownika dynamicznego.
rtp_tip_crosshair_color=Dostosowuje kolor i nieprzezroczystość niestandardowego celownika dynamicznego.
rtp_tip_toggle_aim=Zamiast trzymania przycisku, pozwala włączyć tryb celowania po jednym kliknięciu i wyłączyć go kolejnym.
rtp_tip_smart_scope=Automatycznie przechodzi z powrotem w perspektywę pierwszej osoby podczas używania lunet np. w karabinach snajperskich.
rtp_tip_invert_y=Odwraca działanie myszy w górę i w dół na wzór gier symulujących lot samolotem.
rtp_tip_classic_mode=Wymusza na modelu postaci ciągłe obracanie się w kierunku wyznaczonym przez oko kamery.
rtp_tip_aim_rot_speed=Płynność obrotu postaci podczas celowania.
rtp_tip_transition_speed=Prędkość kinowego lotu kamery. Ustaw na 0, aby przełączać natychmiastowo.
