# Käyttöliittymä
rtp_ui_cam_distance=Kameran etäisyys:
rtp_ui_cam_up=Kameran korkeus:
rtp_ui_crouch_drop=Kameran laskeutuminen kyykyssä:
rtp_ui_cam_right=Vaakasuora siirtymä:
rtp_ui_cam_fov=Näkökenttä (FOV):
rtp_ui_zoom_fov=Tähtäyksen suurennus:
rtp_ui_aiming_btn=Tähtäyspainike:
rtp_ui_sens_mult=Kameran herkkyys:
rtp_ui_hide_crosshair=Piilota tähtäin kun et tähtää
rtp_ui_trace_crosshair=Dynaaminen 3D-tähtäin
rtp_ui_crosshair_size=Tähtäimen koko:
rtp_ui_crosshair_color=Tähtäimen väri:
rtp_ui_toggle_aim=Tähtää napsauttamalla (Toggle)
rtp_ui_smart_scope=Älykäs tähtäin (pois tarkkuuskivääreiltä)
rtp_ui_invert_y=Käännä Y-akseli
rtp_ui_classic_mode=Klassinen liike (kameraan sidottu)
rtp_ui_reset_btn=Palauta oletukset
rtp_ui_enable_btn=Ota kolmas persoona käyttöön
rtp_ui_disable_btn=Poista kolmas persoona käytöstä
rtp_ui_aim_rot_speed=Kiertonopeus tähdätessä:

# Työkaluvihjeet
rtp_tip_cam_distance=Säätää, kuinka kauas hahmon selän taakse kamera sijoitetaan.
rtp_tip_cam_up=Määrittää kameran korkeuden suhteessa pelaajahahmon olkapäähän.
rtp_tip_crouch_drop=Kuinka paljon kamera laskeutuu, kun pelaaja on kyykyssä. (0 = ei laskeudu)
rtp_tip_cam_right=Siirtää kameran näkymää vasemmalle tai oikealle hahmon keskipisteestä.
rtp_tip_cam_fov=Asettaa yleisen näkökentän laajuuden kolmannen persoonan tilassa.
rtp_tip_zoom_fov=Määrittää, kuinka paljon kuva lähenee, kun pidät tähtäyspainiketta pohjassa.
rtp_tip_aiming_btn=Valitse hiiren tai näppäimistön painike, joka aktivoi tarkan tähtäyksen.
rtp_tip_sens_mult=Kameran nopeuskerroin (1 = oletus, < 1 hitaampi, > 1 nopeampi).
rtp_tip_hide_crosshair=Poistaa oletustähtäimen ruudulta silloin, kun ase on lepoasennossa.
rtp_tip_trace_crosshair=Piirtää realistisen osumapisteen, joka näyttää mihin luoti oikeasti osuu 3D-maailmassa.
rtp_tip_crosshair_size=Säätää mukautetun dynaamisen tähtäimen kokoa (pituutta).
rtp_tip_crosshair_color=Säätää mukautetun dynaamisen tähtäimen väriä ja peittävyyttä.
rtp_tip_toggle_aim=Painikkeen pohjassa pitämisen sijaan voit kytkeä tähtäyksen päälle ja pois yhdellä painalluksella.
rtp_tip_smart_scope=Vaihtaa saumattomasti takaisin ensimmäiseen persoonaan, kun katsot tarkkuuskiväärin kiikaritähtäimen läpi.
rtp_tip_invert_y=Kääntää pystysuoran kameranliikkeen päinvastaiseksi (lentisimulaattorien faneille).
rtp_tip_classic_mode=Pakottaa hahmon vartalon kääntymään aina samaan suuntaan, minne kamera katsoo.
rtp_tip_aim_rot_speed=Hahmon kiertonopeuden tasaisuus tähdätessä.

