# Sučelje
rtp_ui_cam_distance=Udaljenost kamere:
rtp_ui_cam_up=Visina kamere:
rtp_ui_crouch_drop=Spuštanje kamere pri čučanju:
rtp_ui_cam_right=Horizontalni pomak:
rtp_ui_cam_fov=Vidno polje (FOV):
rtp_ui_zoom_fov=Količina zumiranja:
rtp_ui_aiming_btn=Tipka za nišanjenje:
rtp_ui_sens_mult=Osjetljivost kamere:
rtp_ui_hide_crosshair=Sakrij nišan izvan ciljanja
rtp_ui_trace_crosshair=Dinamični 3D nišan
rtp_ui_crosshair_size=Veličina nišana:
rtp_ui_crosshair_color=Boja nišana:
rtp_ui_toggle_aim=Ciljanje na klik (Toggle)
rtp_ui_smart_scope=Pametni nišan (isključeno za snajpere)
rtp_ui_invert_y=Obrnuta Y-Os
rtp_ui_classic_mode=Klasično kretanje (vezano uz kameru)
rtp_ui_reset_btn=Vrati na zadano
rtp_ui_enable_btn=Uključi treće lice
rtp_ui_disable_btn=Isključi treće lice
rtp_ui_aim_rot_speed=Brzina rotacije pri ciljanju:

# Oznake alata
rtp_tip_cam_distance=Kontrolira koliko je kamera udaljena od leđa tvog lika.
rtp_tip_cam_up=Podešava visinu kamere iznad ili ispod ramena lika.
rtp_tip_crouch_drop=Koliko se kamera spušta kada igrač čuči. (0 = nema spuštanja)
rtp_tip_cam_right=Pomiče kameru više ulijevo ili udesno u odnosu na središte lika.
rtp_tip_cam_fov=Postavlja opću širinu vidnog polja kamere u igri.
rtp_tip_zoom_fov=Određuje snagu pribiližavanja ekrana kada držiš tipku za precizno nišanjenje.
rtp_tip_aiming_btn=Odaberi tipku tipkovnice ili gumb miša kojim ćeš ulaziti u način nišanjenja.
rtp_tip_sens_mult=Množitelj brzine kamere (1 = zadano, < 1 sporije, > 1 brže).
rtp_tip_hide_crosshair=Uklanja zadani križić s ekrana kako ti ne bi smetao dok samo trčiš.
rtp_tip_trace_crosshair=Prikazuje posebni pokazivač koji u stvarnom vremenu ocrtava 3D putanju tvog metka i točno mjesto udara.
rtp_tip_crosshair_size=Prilagođava veličinu (duljinu) prilagođenog dinamičkog nišana.
rtp_tip_crosshair_color=Prilagođava boju i neprozirnost prilagođenog dinamičkog nišana.
rtp_tip_toggle_aim=Klikni jednom da počneš nišaniti, klikni ponovno za prekid (nema potrebe za držanjem tipke).
rtp_tip_smart_scope=Prilikom gledanja kroz snajperski dalekozor, igra te automatski vraća u prvo lice kako bi izbjegla prodiranje kamere kroz tijelo lika.
rtp_tip_invert_y=Okreće okomitu os kamere naopako, što vole obožavatelji pilotskih igara.
rtp_tip_classic_mode=Zaključava smjer gledanja tvog igrača tako da on uvijek gleda u onom smjeru u kojem je usmjerena kamera.
rtp_tip_aim_rot_speed=Glatkoća rotacije lika pri ciljanju.

