# UI 元素
rtp_ui_cam_distance=摄像机距离:
rtp_ui_cam_up=摄像机高度:
rtp_ui_cam_right=摄像机水平偏移:
rtp_ui_cam_fov=视角(FOV):
rtp_ui_zoom_fov=瞄准放大视角(Zoom FOV):
rtp_ui_aiming_btn=瞄准按键:
rtp_ui_hide_crosshair=未瞄准时隐藏准星
rtp_ui_trace_crosshair=动态3D子弹落点准星
rtp_ui_toggle_aim=点击切换瞄准状态(Toggle)
rtp_ui_smart_scope=智能开镜 (狙击枪自动切换第一人称)
rtp_ui_invert_y=反转Y轴
rtp_ui_classic_mode=经典移动模式 (角色随视角转动)
rtp_ui_reset_btn=重置设置
rtp_ui_enable_btn=启用第三人称
rtp_ui_disable_btn=禁用第三人称

# 提示信息
rtp_tip_cam_distance=控制第三人称摄像机离玩家角色后背有多远。
rtp_tip_cam_up=微调摄像机镜头位于玩家肩膀的什么高度。
rtp_tip_cam_right=控制将主视角置于角色的左肩还是右肩侧面。
rtp_tip_cam_fov=设置第三人称基础的广角视野范围。
rtp_tip_zoom_fov=设置你在举枪瞄准时，屏幕放大的倍率或视觉压缩量。
rtp_tip_aiming_btn=绑定位用于举枪精确瞄准的鼠标或者键盘按键。
rtp_tip_hide_crosshair=在玩家休息、不开镜时自动消除屏幕正中的默认准星。
rtp_tip_trace_crosshair=投射一个精准的红点，为你实时显示子弹在3D空间中击中掩体的真实位置。
rtp_tip_toggle_aim=点击一次按键锁定瞄准状态，再次点击解除。解放你的手指。
rtp_tip_smart_scope=在玩家使用高倍率狙击步枪开镜时，防止由于第三人称导致视野被人物模型遮挡，自动换为第一视角。
rtp_tip_invert_y=翻转上下视角的鼠标移动逻辑，适合习惯飞行模拟器的玩家。
rtp_tip_classic_mode=让人物的身体朝向始终跟随着玩家鼠标移动的方向旋转。
