# Елементи інтерфейсу
rtp_ui_cam_distance=Дистанция камери:
rtp_ui_cam_up=Висота камери:
rtp_ui_crouch_drop=Опускання камери присідом:
rtp_ui_cam_right=Горизонтальне зміщення:
rtp_ui_cam_fov=Кут огляду (FOV):
rtp_ui_zoom_fov=Наближення при прицілюванні:
rtp_ui_aiming_btn=Кнопка прицілювання:
rtp_ui_sens_mult=Чутливість камери:
rtp_ui_hide_crosshair=Ховати приціл без прицілювання
rtp_ui_trace_crosshair=Динамічний 3D приціл (траєкторія)
rtp_ui_crosshair_size=Розмір прицілу:
rtp_ui_crosshair_color=Колір прицілу:
rtp_ui_toggle_aim=Прицілювання по кліку (Toggle)
rtp_ui_smart_scope=Розумний приціл (вимк. для снайперок)
rtp_ui_invert_y=Інвертувати вісь Y
rtp_ui_classic_mode=Класичний рух (від камери)
rtp_ui_reset_btn=Скинути налаштування
rtp_ui_enable_btn=Увімкнути режим від 3-ї особи
rtp_ui_disable_btn=Вимкнути режим від 3-ї особи
rtp_ui_aim_rot_speed=Плавність повороту (приціл):
rtp_ui_transition_speed=Швидкість переходу камери
rtp_ui_block_attack2=Блокувати альтернативний вогонь під час прицілювання

# Підказки
rtp_tip_cam_distance=Визначає, наскільки сильно камера віддаляється від спини вашого персонажа.
rtp_tip_cam_up=Регулює висоту розміщення камери над плечем або над головою гравця.
rtp_tip_crouch_drop=Наскільки камера опускається вниз, коли гравець сидить. (0 = не опускається)
rtp_tip_cam_right=Дозволяє змістити погляд камери ліворуч або праворуч відносно центру спини.
rtp_tip_cam_fov=Встановлює базовий, загальний кут зору для гри у цьому режимі.
rtp_tip_zoom_fov=Вказує наскільки інтенсивно камера фокусується "наближає", коли ви натискаєте на кнопку прицілювання.
rtp_tip_aiming_btn=Клавіша на клавіатурі або кнопка миші для переходу у точний снайперський режим.
rtp_tip_sens_mult=Множник швидкості камери (1 = за замовчуванням, < 1 повільніше, > 1 швидше).
rtp_tip_hide_crosshair=Приховує стандартний перехресний приціл на екрані, якщо ви біжите або не цілитеся.
rtp_tip_trace_crosshair=Малює реальну точку влучання кулі, ідеально враховуючи перешкоди у відкритому 3D просторі.
rtp_tip_crosshair_size=Змінює розмір (довжину) користувацького динамічного прицілу.
rtp_tip_crosshair_color=Змінює колір і прозорість користувацького динамічного прицілу.
rtp_tip_toggle_aim=Вмикає режим 'залипання': натиснули раз для прицілювання, вдруге — для переходу у звичайний стан.
rtp_tip_smart_scope=Автоматично переводить гру від першої особи при використанні оптичних прицілів (як у снайперок).
rtp_tip_invert_y=Міняє напрямок руху миші вверх-вниз на протилежний, ніби ви в авіасимуляторі.
rtp_tip_classic_mode=Змушує модельку вашого персонажа завжди повертатися туди, куди дивиться камера.
rtp_tip_aim_rot_speed=Швидкість повороту персонажа під час прицілювання.
rtp_tip_transition_speed=Швидкість кінематографічного польоту камери. Встановіть на 0 для миттєвого перемикання.
rtp_tip_block_attack2=Запобігає пострілу з вторинної атаки зброї під час прицілювання від третьої особи. Вимкніть це, якщо прицілювання ламає кастомні бази зброї на кшталт ARC9.
