# Elementos de Interface
rtp_ui_cam_distance=Distância da Câmara:
rtp_ui_cam_up=Altura da Câmara:
rtp_ui_crouch_drop=Queda da câmara ao agachar:
rtp_ui_cam_right=Deslocamento Horizontal:
rtp_ui_cam_fov=Campo de Visão (FOV):
rtp_ui_zoom_fov=Nível de Zoom da Mira:
rtp_ui_aiming_btn=Botão de Mirar:
rtp_ui_sens_mult=Sensibilidade da Câmara:
rtp_ui_hide_crosshair=Ocultar mira fora de combate
rtp_ui_trace_crosshair=Mira 3D dinâmica de impacto
rtp_ui_crosshair_size=Tamanho da mira:
rtp_ui_crosshair_color=Cor da mira:
rtp_ui_toggle_aim=Mirar por Clique (Alternar)
rtp_ui_smart_scope=Mira Inteligente (desativar em sniper)
rtp_ui_invert_y=Inverter o Eixo Y
rtp_ui_classic_mode=Movimento Clássico (fixo na câmara)
rtp_ui_reset_btn=Repor Predefinições
rtp_ui_enable_btn=Ativar 3ª Pessoa
rtp_ui_disable_btn=Desativar 3ª Pessoa
rtp_ui_aim_rot_speed=Velocidade de Rotação ao Mirar:
rtp_ui_transition_speed=Velocidade de Transição da Câmara
rtp_ui_block_attack2=Bloquear fogo alternativo ao mirar

# Dicas Verbais
rtp_tip_cam_distance=Ajusta a distância da câmara em relação às costas do teu personagem.
rtp_tip_cam_up=Define a altura em que a câmara se situa por cima do ombro do jogador.
rtp_tip_crouch_drop=O quanto a câmara desce ao agachar. (0 = sem queda)
rtp_tip_cam_right=Desloca a visão do jogador para a esquerda ou direita do modelo 3D.
rtp_tip_cam_fov=Controla a amplitude da visão periférica durante o modo na terceira pessoa.
rtp_tip_zoom_fov=Determina a força de aproximação do ecrã ao segurar o botão de mira.
rtp_tip_aiming_btn=Designa o botão do rato ou tecla a utilizar para fazer pontaria precisa.
rtp_tip_sens_mult=Multiplicador de velocidade da câmara (1 = predefinição, < 1 mais lento, > 1 mais rápido).
rtp_tip_hide_crosshair=Remove o cursor central caso não estejas com a arma levantada para disparar.
rtp_tip_trace_crosshair=Desenha uma mira especial que indica no mundo físico o verdadeiro local de impacto do tiro.
rtp_tip_crosshair_size=Ajusta o tamanho (comprimento) da mira dinâmica personalizada.
rtp_tip_crosshair_color=Ajusta a cor e a opacidade da mira dinâmica personalizada.
rtp_tip_toggle_aim=Em vez de manter o botão premido, carrega uma vez para mirar e outra para soltar.
rtp_tip_smart_scope=Muda automaticamente para a perspetiva de primeira pessoa ao utilizar miras telescópicas de franco-atirador.
rtp_tip_invert_y=Vira ao contrário o movimento vertical da câmara (semelhante a controlos de simuladores de voo).
rtp_tip_classic_mode=O corpo do personagem passa a rodar continuamente para a direção apontada pela câmara.
rtp_tip_aim_rot_speed=Suavidade da rotação da personagem ao mirar.
rtp_tip_transition_speed=Velocidade do voo cinematográfico da câmara. Defina como 0 para mudança instantânea.
rtp_tip_block_attack2=Impede o disparo do ataque secundário da arma enquanto mira na terceira pessoa. Desative isso se a mira neutralizar bases de armas personalizadas como o ARC9.
