# Gebruikersinterface
rtp_ui_cam_distance=Camera Afstand:
rtp_ui_cam_up=Camera Hoogte:
rtp_ui_crouch_drop=Camera-daling bij hurken:
rtp_ui_cam_right=Horizontale Verschuiving:
rtp_ui_cam_fov=Gezichtsveld (FOV):
rtp_ui_zoom_fov=Zoomwaarde tijdens richten:
rtp_ui_aiming_btn=Richtknop:
rtp_ui_sens_mult=Cameragevoeligheid:
rtp_ui_hide_crosshair=Verberg vizier als er niet gericht wordt
rtp_ui_trace_crosshair=Dynamisch 3D vizier
rtp_ui_crosshair_size=Grootte vizier:
rtp_ui_crosshair_color=Kleur vizier:
rtp_ui_toggle_aim=Richten met klik (Toggle)
rtp_ui_smart_scope=Slim richten (uit voor sluipschuttersgeweer)
rtp_ui_invert_y=Keer Y-as om
rtp_ui_classic_mode=Klassieke beweging (gekoppeld aan camera)
rtp_ui_reset_btn=Instellingen herstellen
rtp_ui_enable_btn=Derdepersoon Inschakelen
rtp_ui_disable_btn=Derdepersoon Uitschakelen

# Tooltips
rtp_tip_cam_distance=Bepaalt hoe ver de camera achter de rug van het personage staat.
rtp_tip_cam_up=Regelt de hoogte van de camera ten opzichte van de schouder van het personage.
rtp_tip_crouch_drop=Hoeveel de camera naar beneden gaat wanneer de speler hurkt. (0 = geen daling)
rtp_tip_cam_right=Zet de camera meer naar de linker- of rechterkant vanuit het midden van de rug.
rtp_tip_cam_fov=Past de breedte aan van het algehele gezichtsveld.
rtp_tip_zoom_fov=Bepaalt hoeveel er op het scherm wordt ingezoomd als je de richtknop indrukt.
rtp_tip_aiming_btn=Wijs de muis- of toetsenbordknop toe om de precisierichtmodus in te schakelen.
rtp_tip_sens_mult=Cameranelheid vermenigvuldiger (1 = standaard, < 1 langzamer, > 1 sneller).
rtp_tip_hide_crosshair=Laat het standaard dradenkruis verdwijnen als je je wapen in rust of op je rug hebt.
rtp_tip_trace_crosshair=Toont de werkelijke inslagplek van je kogels in de 3D-wereld in plaats van het dode midden van je scherm.
rtp_tip_crosshair_size=Past de grootte (lengte) van het aangepaste dynamische vizier aan.
rtp_tip_crosshair_color=Past de kleur en ondoorzichtigheid van het aangepaste dynamische vizier aan.
rtp_tip_toggle_aim=Je hoeft de richtknop niet meer ingedrukt te houden, eenmaal klikken om te richten is genoeg.
rtp_tip_smart_scope=Schakelt de derdepersoonsweergave direct uit als je door het vergrootvizier van een sluipschuttersgeweer kijkt.
rtp_tip_invert_y=Draait het besturingsschema op de Y-as om, alsof je de stuurknuppel van een vliegtuig bedient.
rtp_tip_classic_mode=Het personage roteert bij elke draaiing automatisch permanent met de camerahoek mee.
