# UI 元素
rtp_ui_cam_distance=攝影機距離:
rtp_ui_cam_up=攝影機高度:
rtp_ui_cam_right=攝影機水平偏移:
rtp_ui_cam_fov=視角 (FOV):
rtp_ui_zoom_fov=瞄準放大視角 (Zoom FOV):
rtp_ui_aiming_btn=瞄準按鍵:
rtp_ui_sens_mult=攝影機靈敏度：
rtp_ui_hide_crosshair=未瞄準時隱藏準星
rtp_ui_trace_crosshair=動態 3D 子彈落點準星
rtp_ui_toggle_aim=點擊切換瞄準狀態 (Toggle)
rtp_ui_smart_scope=智慧開鏡 (狙擊槍自動切換第一人稱)
rtp_ui_invert_y=反轉 Y 軸
rtp_ui_classic_mode=經典移動模式 (角色隨視角轉動)
rtp_ui_reset_btn=重設設定
rtp_ui_enable_btn=啟用第三人稱
rtp_ui_disable_btn=停用第三人稱

# 提示資訊
rtp_tip_cam_distance=控制第三人稱攝影機離玩家角色後背有多遠。
rtp_tip_cam_up=微調攝影機鏡頭位於玩家肩膀的什麼高度。
rtp_tip_cam_right=控制將主視角置於角色的左肩還是右肩側面。
rtp_tip_cam_fov=設定第三人稱基礎的廣角視野範圍。
rtp_tip_zoom_fov=設定你在舉槍瞄準時，螢幕放大的倍率或視覺壓縮量。
rtp_tip_aiming_btn=綁定位於舉槍精確瞄準的滑鼠或者鍵盤按鍵。
rtp_tip_sens_mult=攝影機速度乘數（1 = 預設，< 1 較慢，> 1 較快）。
rtp_tip_hide_crosshair=在玩家休息、不開鏡時自動隱藏螢幕正中的預設準星。
rtp_tip_trace_crosshair=投射一個精準的紅點，為你即時顯示子彈在 3D 空間中擊中掩體的真實位置。
rtp_tip_toggle_aim=點擊一次按鍵鎖定瞄準狀態，再次點擊解除，解放你的手指。
rtp_tip_smart_scope=在玩家使用高倍率狙擊步槍開鏡時，防止由於第三人稱導致視野被人物模型遮擋，自動換為第一視角。
rtp_tip_invert_y=翻轉上下視角的滑鼠移動邏輯，適合習慣飛行模擬器的玩家。
rtp_tip_classic_mode=讓人物的身體朝向始終跟隨著玩家滑鼠移動的方向旋轉。
