# Interfaz de usuario
rtp_ui_cam_distance=Distancia de la cámara:
rtp_ui_cam_up=Altura de la cámara:
rtp_ui_crouch_drop=Descenso de cámara al agacharse:
rtp_ui_cam_right=Desplazamiento horizontal:
rtp_ui_cam_fov=Campo de visión:
rtp_ui_zoom_fov=Magnitud de zoom:
rtp_ui_aiming_btn=Botón de apuntar:
rtp_ui_sens_mult=Sensibilidad de la cámara:
rtp_ui_hide_crosshair=Ocultar mira sin apuntar
rtp_ui_trace_crosshair=Mira 3D dinámica
rtp_ui_crosshair_size=Tamaño de la mira:
rtp_ui_crosshair_color=Color de la mira:
rtp_ui_toggle_aim=Apuntar con un clic (Alternar)
rtp_ui_smart_scope=Mira inteligente (desactivada en francotiradores)
rtp_ui_smart_scope_threshold=Umbral de FOV para Smart Scope:
rtp_ui_invert_y=Invertir eje Y
rtp_ui_classic_mode=Movimiento clásico (fijo a la cámara)
rtp_ui_reset_btn=Restablecer
rtp_ui_enable_btn=Activar 3ra persona
rtp_ui_disable_btn=Desactivar 3ra persona

# Descripciones útiles
rtp_tip_cam_distance=Configura qué tan lejos se sitúa la cámara detrás de tu jugador.
rtp_tip_cam_up=Ajusta el margen de altura de la cámara en relación al hombro del jugador.
rtp_tip_crouch_drop=Cuánto baja la cámara cuando el jugador se agacha. (0 = sin descenso)
rtp_tip_cam_right=Mueve la posición de la cámara hacia la izquierda o hacia la derecha.
rtp_tip_cam_fov=Define cuán amplio será tu campo visual en el modo de tercera persona.
rtp_tip_zoom_fov=Controla la intensidad del acercamiento cuando presionas el botón de apuntar.
rtp_tip_aiming_btn=El botón del ratón o la tecla designados para el modo de precisión.
rtp_tip_sens_mult=Multiplicador de velocidad de la cámara (1 = predeterminado, < 1 más lento, > 1 más rápido).
rtp_tip_hide_crosshair=Borra la mira predeterminada de la pantalla mientras tu arma está en reposo.
rtp_tip_trace_crosshair=Dibuja un marcador preciso indicando dónde exactamente impactarán los disparos en el mundo 3D.
rtp_tip_crosshair_size=Ajusta el tamaño (longitud) de la mira dinámica personalizada.
rtp_tip_crosshair_color=Ajusta el color y la opacidad de la mira dinámica personalizada.
rtp_tip_toggle_aim=En lugar de mantener pulsado, permite alternar la mira con solo un clic.
rtp_tip_smart_scope=Cambia de inmediato a primera persona al utilizar miras telescópicas de gran aumento.
rtp_tip_smart_scope_threshold=Establece el umbral de FOV por debajo del cual el Smart Scope cambia automáticamente a primera persona.
rtp_tip_invert_y=Invierte la rotación vertical, para los que juegan con controles invertidos (tipo avión).
rtp_tip_classic_mode=Hace que el cuerpo del personaje siempre mire hacia la misma dirección que la cámara.
