# Элементы интерфейса
rtp_ui_cam_distance=Дистанция камеры:
rtp_ui_cam_up=Смещение по вертикали:
rtp_ui_cam_right=Смещение по горизонтали:
rtp_ui_cam_fov=Угол обзора (FOV):
rtp_ui_zoom_fov=Приближение в прицеле:
rtp_ui_aiming_btn=Кнопка прицеливания:
rtp_ui_sens_mult=Чувствительность:
rtp_ui_hide_crosshair=Скрывать прицел вне стрельбы
rtp_ui_trace_crosshair=Динамический 3D прицел (траектория)
rtp_ui_toggle_aim=Прицеливание по клику (Toggle)
rtp_ui_smart_scope=Умный прицел (откл. для снайперок)
rtp_ui_invert_y=Инвертировать ось Y
rtp_ui_classic_mode=Классическое движение (от камеры)
rtp_ui_reset_btn=Сбросить настройки
rtp_ui_enable_btn=Включить вид от 3-го лица
rtp_ui_disable_btn=Выключить вид от 3-го лица

# Подсказки
rtp_tip_cam_distance=Отвечает за то, насколько далеко камера находится за спиной персонажа.
rtp_tip_cam_up=Регулирует высоту расположения камеры над плечом игрока.
rtp_tip_cam_right=Позволяет сместить камеру влево или вправо относительно центра спины.
rtp_tip_cam_fov=Устанавливает оптимальный угол зрения (косвенно влияет на перспективу).
rtp_tip_zoom_fov=Определяет, насколько сильно "зумится" камера при нажатии кнопки прицела.
rtp_tip_aiming_btn=Клавиша на клавиатуре или кнопка мыши, отвечающая за вход в режим точного прицеливания.
rtp_tip_sens_mult=Множитель скорости камеры (1 = стандарт, < 1 замедление, > 1 ускорение).
rtp_tip_hide_crosshair=Убирает стандартное перекрестие с экрана, когда ваш персонаж бежит или не целится.
rtp_tip_trace_crosshair=Отображает реальную точку попадания пули, учитывая препятствия на линии огня.
rtp_tip_toggle_aim=Включает режим залипания: нажмите один раз для прицеливания, второй — для выхода.
rtp_tip_smart_scope=Автоматически переводит игру от первого лица при использовании мощной оптики (снайперских винтовок).
rtp_tip_invert_y=Меняет направление движения мыши вверх-вниз на противоположное (как в авиасимуляторах).
rtp_tip_classic_mode=Заставляет модель персонажа всегда поворачиваться вслед за движением камеры.
