# Interface
rtp_ui_cam_distance=Distância da Câmera:
rtp_ui_cam_up=Altura da Câmera:
rtp_ui_cam_right=Deslocamento Horizontal:
rtp_ui_cam_fov=Campo de Visão (FOV):
rtp_ui_zoom_fov=Nível do Zoom de Mira:
rtp_ui_aiming_btn=Botão de Mirar:
rtp_ui_sens_mult=Sensibilidade da Câmera:
rtp_ui_hide_crosshair=Ocultar mira fora de combate
rtp_ui_trace_crosshair=Mira 3D dinâmica de impacto
rtp_ui_toggle_aim=Mira por Clique (Alternar)
rtp_ui_smart_scope=Mira Inteligente (sem 3ª pessoa para SNIPER)
rtp_ui_smart_scope_threshold=Limite de FOV para Smart Scope:
rtp_ui_invert_y=Inverter o eixo Y
rtp_ui_classic_mode=Movimento Clássico (preso na câmera)
rtp_ui_reset_btn=Restaurar Padrão
rtp_ui_enable_btn=Ativar 3ª Pessoa
rtp_ui_disable_btn=Desativar 3ª Pessoa

# Descrições
rtp_tip_cam_distance=Altera o quanto a câmera se afasta das costas do seu jogador.
rtp_tip_cam_up=Regula o nível de elevação da visão acima do ombro do modelo.
rtp_tip_cam_right=Move a visão do jogador para os lados do modelo 3D (esquerda ou direita).
rtp_tip_cam_fov=Ajusta quão ampla é a visão periférica durante o modo em terceira pessoa.
rtp_tip_zoom_fov=Ajusta o nível de aproximação que a tela recebe ao segurar o botão de mira.
rtp_tip_aiming_btn=Liga o botão do mouse ou tecla desejada para acionar o zoom.
rtp_tip_sens_mult=Multiplicador de velocidade da câmera (1 = padrão, < 1 mais lento, > 1 mais rápido).
rtp_tip_hide_crosshair=Remove o cursor central padrão se você não está ativamente mirando.
rtp_tip_trace_crosshair=Desenha um cursor realista mostrando no mapa o exato traçado do disparo.
rtp_tip_toggle_aim=Ao invés de segurar, aperte o botão apenas uma vez para fixar em modo de visada.
rtp_tip_smart_scope=Evita problemas ao forçar primeira pessoa quando uma luneta de aumento de francoatirador é usada.
rtp_tip_smart_scope_threshold=Define o limite de FOV abaixo do qual o Smart Scope muda automaticamente para a primeira pessoa.
rtp_tip_invert_y=Puxar o mouse para você inclina a câmera pra cima; útil para simuladores.
rtp_tip_classic_mode=Força o personagem a encarar permanentemente onde a câmera está focando.
