# Διεπαφή Χρήστη
rtp_ui_cam_distance=Απόσταση Κάμερας:
rtp_ui_cam_up=Ύψος Κάμερας:
rtp_ui_crouch_drop=Βύθισμα Κάμερας στο Σκύψιμο:
rtp_ui_cam_right=Οριζόντια Μετατόπιση:
rtp_ui_cam_fov=Οπτικό Πεδίο (FOV):
rtp_ui_zoom_fov=Ποσοστό Ζουμ Στόχευσης:
rtp_ui_aiming_btn=Πλήκτρο Στόχευσης:
rtp_ui_sens_mult=Ευαισθησία κάμερας:
rtp_ui_hide_crosshair=Απόκρυψη στόχαστρου εκτός στόχευσης
rtp_ui_trace_crosshair=Δυναμικό 3D στόχαστρο (Τροχιά)
rtp_ui_crosshair_size=Μέγεθος στόχαστρου:
rtp_ui_crosshair_color=Χρώμα στόχαστρου:
rtp_ui_toggle_aim=Στόχευση με κλικ (Εναλλαγή)
rtp_ui_smart_scope=Έξυπνη Στόχευση (απενεργ. σε sniper)
rtp_ui_invert_y=Αντιστροφή Άξονα Y
rtp_ui_classic_mode=Κλασική κίνηση (κλείδωμα στην κάμερα)
rtp_ui_reset_btn=Επαναφορά Ρυθμίσεων
rtp_ui_enable_btn=Ενεργοποίηση 3ου Προσώπου
rtp_ui_disable_btn=Απενεργοποίηση 3ου Προσώπου

# Επεξηγήσεις
rtp_tip_cam_distance=Καθορίζει πόσο μακριά πίσω από την πλάτη του χαρακτήρα σας βρίσκεται η κάμερα.
rtp_tip_cam_up=Ρυθμίζει το ύψος της κάμερας πάνω ή κάτω από τους ώμους του παίκτη.
rtp_tip_crouch_drop=Πόσο χαμηλώνει η κάμερα όταν ο παίκτης σκύβει. (0 = χωρίς βύθισμα)
rtp_tip_cam_right=Μετατοπίζει την κάμερα προς τα αριστερά ή τα δεξιά από το κέντρο του χαρακτήρα.
rtp_tip_cam_fov=Ρυθμίζει το γενικό εύρος του οπτικού σας πεδίου.
rtp_tip_zoom_fov=Καθορίζει πόσο έντονα ζουμάρει η οθόνη όταν πατάτε το κουμπί στόχευσης.
rtp_tip_aiming_btn=Επιλέγει το πλήκτρο του ποντικιού ή του πληκτρολογίου για την ακριβή στόχευση.
rtp_tip_sens_mult=Πολλαπλασιαστής ταχύτητας κάμερας (1 = προεπιλογή, < 1 πιο αργά, > 1 πιο γρήγορα).
rtp_tip_hide_crosshair=Αφαιρεί το προεπιλεγμένο σταυρόνημα από την οθόνη όταν δεν σκοπεύετε.
rtp_tip_trace_crosshair=Εμφανίζει ένα ρεαλιστικό σημάδι κρούσης, δείχνοντας πού ακριβώς χτυπάει η σφαίρα στον 3D κόσμο.
rtp_tip_crosshair_size=Προσαρμόζει το μέγεθος (μήκος) του προσαρμοσμένου δυναμικού στόχαστρου.
rtp_tip_crosshair_color=Προσαρμόζει το χρώμα και την αδιαφάνεια του προσαρμοσμένου δυναμικού στόχαστρου.
rtp_tip_toggle_aim=Αντί να κρατάτε πατημένο το πλήκτρο, επιτρέπει την ενεργοποίηση / απενεργοποίηση της στόχευσης με ένα μόνο κλικ.
rtp_tip_smart_scope=Επιστρέφει αυτόματα την κάμερα σε πρώτο πρόσωπο όταν χρησιμοποιείτε διόπτρες ελεύθερου σκοπευτή.
rtp_tip_invert_y=Αντιστρέφει την κατακόρυφη κίνηση του ποντικιού (όπως στα παιχνίδια προσομοίωσης πτήσης).
rtp_tip_classic_mode=Κλειδώνει την κατεύθυνση του σώματος του παίκτη, ώστε να κοιτάζει πάντα προς τα εκεί που βλέπει η κάμερα.
