# Elementi dell'interfaccia
rtp_ui_cam_distance=Distanza telecamera:
rtp_ui_cam_up=Altezza telecamera:
rtp_ui_crouch_drop=Abbassamento telecamera accovacciati:
rtp_ui_cam_right=Spostamento orizzontale:
rtp_ui_cam_fov=Campo visivo:
rtp_ui_zoom_fov=Zoom del mirino:
rtp_ui_aiming_btn=Tasto di mira:
rtp_ui_sens_mult=Sensibilità fotocamera:
rtp_ui_hide_crosshair=Nascondi mirino senza mira
rtp_ui_trace_crosshair=Mirino 3D dinamico
rtp_ui_crosshair_size=Dimensione mirino:
rtp_ui_crosshair_color=Colore mirino:
rtp_ui_toggle_aim=Mira al clic (Toggle)
rtp_ui_smart_scope=Mira intelligente (disattiva l'ottica)
rtp_ui_invert_y=Inverti l'asse Y
rtp_ui_classic_mode=Movimento classico (fisso alla telecamera)
rtp_ui_reset_btn=Ripristina
rtp_ui_enable_btn=Attiva in 3a Persona
rtp_ui_disable_btn=Disattiva in 3a Persona

# Suggerimenti (Tooltips)
rtp_tip_cam_distance=Stabilisce la lontananza della telecamera dalle spalle del tuo personaggio.
rtp_tip_cam_up=Modifica l'altezza della telecamera posizionandola sopra o a livello del giocatore.
rtp_tip_crouch_drop=Di quanto si abbassa la telecamera quando il giocatore è accovacciato. (0 = nessun abbassamento)
rtp_tip_cam_right=Posiziona la visuale più sul lato sinistro o destro rispetto alla schiena.
rtp_tip_cam_fov=Regola l'ampiezza generale della visuale in terza persona.
rtp_tip_zoom_fov=Determina l'intensità di ingrandimento visivo quando premi il tasto di mira.
rtp_tip_aiming_btn=Assegna il tasto o clicca il pulsante del mouse utilizzato per mirare di precisione.
rtp_tip_sens_mult=Moltiplicatore velocità fotocamera (1 = predefinito, < 1 più lento, > 1 più veloce).
rtp_tip_hide_crosshair=Rimuove il mirino standard dallo schermo quando l'arma non è in posizione di tiro.
rtp_tip_trace_crosshair=Mostra un punto di impatto reale nel mondo 3D, tenendo conto degli ostacoli fisici.
rtp_tip_crosshair_size=Regola la dimensione (lunghezza) del mirino dinamico personalizzato.
rtp_tip_crosshair_color=Regola il colore e l'opacità del mirino dinamico personalizzato.
rtp_tip_toggle_aim=Permette di mirare cliccando una volta, senza dover tenere premuto il tasto.
rtp_tip_smart_scope=Torna istantaneamente in prima persona quando utilizzi armi con mirino da cecchino.
rtp_tip_invert_y=Capovolge i comandi verticali della telecamera (es. muovi in alto e guarda in basso).
rtp_tip_classic_mode=Collega il modello fisico del personaggio all'orientamento costante della telecamera.
