name: Deploy to Steam Workshop

on:
  push:
    tags:
      - 'v*.*.*' # Run only when creating tags like v1.0.0

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Addon Title with Version
        run: |
          # The system variable GITHUB_REF_NAME contains the name of the pushed tag (e.g., v1.0.0)
          $VERSION = $env:GITHUB_REF_NAME
          Write-Host "Appending version $VERSION to addon.json title..."
          
          # Use PowerShell to update the title field and overwrite the file
          $json = Get-Content addon.json -Raw | ConvertFrom-Json
          $json.title = "$($json.title) $VERSION"
          $json | ConvertTo-Json -Depth 10 | Set-Content addon.json
          
          # Output the result to logs for verification
          Get-Content addon.json

      - name: Publish to Steam Workshop
        uses: Earu/GSW-action@V3.0
        with:
          workshop-id: '1620191091'
          account-name: ${{ secrets.STEAM_USERNAME }}
          account-password: ${{ secrets.STEAM_PASSWORD }}
