# Éléments d'interface
rtp_ui_cam_distance=Distance de la caméra:
rtp_ui_cam_up=Hauteur de la caméra:
rtp_ui_cam_right=Décalage horizontal:
rtp_ui_cam_fov=Champ de vision:
rtp_ui_zoom_fov=Zoom de visée:
rtp_ui_aiming_btn=Touche de visée:
rtp_ui_sens_mult=Sensibilité de la caméra :
rtp_ui_hide_crosshair=Masquer le réticule hors visée
rtp_ui_trace_crosshair=Réticule 3D dynamique
rtp_ui_toggle_aim=Visée par clic (Bascule)
rtp_ui_smart_scope=Visée intelligente (désactivé pour sniper)
rtp_ui_invert_y=Inverser l'axe Y
rtp_ui_classic_mode=Mouvement classique (lié à la caméra)
rtp_ui_reset_btn=Réinitialiser
rtp_ui_enable_btn=Activer la 3ème Personne
rtp_ui_disable_btn=Désactiver la 3ème Personne

# Infobulles
rtp_tip_cam_distance=Ajuste l'éloignement de la caméra par rapport à votre personnage.
rtp_tip_cam_up=Règle la hauteur de la caméra, pour voir au-dessus ou au niveau de l'épaule.
rtp_tip_cam_right=Décale la caméra sur le côté gauche ou droit de votre personnage.
rtp_tip_cam_fov=Modifie la largeur du champ de vision global en vue à la 3ème personne.
rtp_tip_zoom_fov=Définit la puissance du zoom lorsque vous épaulez votre arme.
rtp_tip_aiming_btn=Assignez le bouton de la souris ou la touche clavier pour viser.
rtp_tip_sens_mult=Multiplicateur de vitesse de la caméra (1 = par défaut, < 1 plus lent, > 1 plus rapide).
rtp_tip_hide_crosshair=Permet de rendre le réticule invisible lorsque l'arme est au repos.
rtp_tip_trace_crosshair=Affiche un réticule adaptatif qui vous indique le point d'impact réel de la balle.
rtp_tip_toggle_aim=Active le mode bascule pour la visée : un clic pour viser, un autre pour relâcher.
rtp_tip_smart_scope=Passe automatiquement à la vue première personne lors de l'utilisation de lunettes de sniper.
rtp_tip_invert_y=Inverse la commande verticale de la caméra pour ceux qui préfèrent ce type de contrôle.
rtp_tip_classic_mode=Mode de jeu rétro : le corps du personnage s'oriente toujours là où vous regardez.
